name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: bug_report
    attributes:
      label: Bug Report
      value: |
        **Description**

        xxx

        **Expected behavior**

        xxx

        **Markleaf version:** xxx

        **Browser:** xxx
    validations:
      required: true
